### ISSUE TITLE
Github to local

### ISSUE THREAD

**Issue by sksourou** [CyCoreSystems/docker-meteor#16]
Hi, i always start my docker containair like that : 

```
#docker-compose.yml

meteor:  
  image:  ulexus/meteor
  ports:
   - "80:80"
  links:
   - mongo
  environment:
   - REPO=https://github.com/...
   - ROOT_URL=http://192.168.59.103
mongo:  
  image: mongo
  ports:
  - "27017:27017"
```

i would like to start my containair with my local app now. Can i create a git on the app directory and use it like `repo=d:/path/to/myapp` ? or i need an online git ? 

if i cant use a local git what i need to add on the docker-compose.yml ? 

when i try to just add   

```
volumes:
    - .:/app
```

he stay bloqued `waiting for the connections on port 27017`

ty, sorry for my really bad english.
